version: "3.9"
services:
  frontend-schrittzaehler-challenge:
    container_name: frontend-schrittzaehler-challenge
    build: ./../frontend-schrittzaehler-challenge/
    ports:
      - 9000:80

  backend-schrittzaehler-challenge:
    container_name: backend-schrittzaehler-challenge
    build: ./../backend-schrittzaehler-challenge/
    environment:
      - DATASOURCE=schrittzaehler-challenge-postgres
    ports:
      - 8080:8080
    networks:
      - schrittzaehler-challenge-network

  schrittzaehler-challenge-postgres:
    container_name: schrittzaehler-challenge-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - schrittzaehler-challenge-network
    volumes:
      - schrittzaehler-challenge-postgres:/var/lib/postgresql/data


  schrittzaehler-challenge-pgadmin:
    container_name:
      schrittzaehler-challenge-pgadmin
    image: dpage/pgadmin4:5.1
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=sacha_vogel@sluz.ch
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 4000:80
    volumes:
      - schrittzaehler-challenge-pgadmin:/var/lib/pgadmin
    networks:
      - schrittzaehler-challenge-network

  schrittzaehler-challenge-redis:
    container_name: schrittzaehler-challenge-redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - schrittzaehler-challenge-network
    volumes:
      - schrittzaehler-challenge-redis:/data

volumes:
  schrittzaehler-challenge-pgadmin:
  schrittzaehler-challenge-postgres:
  schrittzaehler-challenge-redis:

networks:
  schrittzaehler-challenge-network:
    driver: bridge
    name: schrittzaehler-challenge-network