CREATE TABLE public.competition (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name varchar(255) NOT NULL,
    start_date date NULL,
    end_date date NULL,
    state varchar(255) NOT NULL,
    CONSTRAINT pk_competition PRIMARY KEY (id)
);

CREATE TABLE public.group (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    competition_id bigint,
    groupname varchar(255) NOT NULL,
    CONSTRAINT pk_group PRIMARY KEY (id),
    CONSTRAINT fk_competition_id FOREIGN KEY (competition_id)
        REFERENCES competition (id) MATCH SIMPLE
);

CREATE TABLE public.user (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id bigint,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    daily_step_goal INT NULL,
    user_role varchar(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT fk_group_id FOREIGN KEY (group_id)
        REFERENCES group (id) MATCH SIMPLE
);

CREATE TABLE public.step (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint,
    number_of_steps INT NOT NULL,
    creation_date date NOT NULL,
    CONSTRAINT pk_step PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id)
        REFERENCES user (id) MATCH SIMPLE
);