CREATE TABLE public.competition (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name varchar(255) NOT NULL,
    start_date date NULL,
    end_date date NULL,
    state varchar(255) NOT NULL,
    CONSTRAINT pk_competition PRIMARY KEY (id)
);

CREATE TABLE public.groups (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    competition_id bigint NOT NULL,
    groupname varchar(255) NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id),
    CONSTRAINT fk_competition_id FOREIGN KEY (competition_id)
        REFERENCES competition (id) MATCH SIMPLE
);

CREATE TABLE public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    groups_id bigint NOT NULL,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    daily_step_goal INT NULL,
    user_role varchar(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_groups_id FOREIGN KEY (groups_id)
        REFERENCES groups (id) MATCH SIMPLE
);

CREATE TABLE public.steps (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    users_id bigint NOT NULL,
    number_of_steps INT NOT NULL,
    creation_date date NOT NULL,
    CONSTRAINT pk_steps PRIMARY KEY (id),
    CONSTRAINT fk_users_id FOREIGN KEY (users_id)
        REFERENCES users (id) MATCH SIMPLE
);